[versions]
kotlin = "2.3.0-RC3"
quickMpp = "0.21"

[libraries]
equalsTester = { module = "io.github.adokky:equals-tester", version = "1.1.0" }
bitvector = { module = "io.github.adokky:bitvector", version = "0.9.2" }

[plugins]
quick-mpp = { id = "io.github.adokky.quick-mpp", version.ref = "quickMpp" }
quick-publish = { id = "io.github.adokky.quick-publish", version.ref = "quickMpp" }
